#!/usr/bin/env bash

echo "*********** Installing Carthage ***********"
brew update
brew install carthage --HEAD

echo "*********** Installing dependencies with Carthage ***********"
carthage bootstrap --no-build
ret=$?
if [ $ret -ne 0 ]; then 
	echo "⚠ Carthage bootstrap command failed, here are the logs (maybe)"
	find $TMPDIR -type f -name "carthage-xcodebuild.*" -exec cat {} \;
	exit $ret
fi

find Carthage/Checkouts -type -f -name "*iOS.xcscheme" -delete

carthage build
ret=$?
if [ $ret -ne 0 ]; then 
	echo "⚠ Carthage build command failed, here are the logs (maybe)"
	find $TMPDIR -type f -name "carthage-xcodebuild.*" -exec cat {} \;
	exit $ret
fi
echo "*********** Installing ruby dependencies ***********"
gem install bundler --no-rdoc --no-ri
bundle install
